project:
  type: website
  resources: 
      - papers/
      - images/
      - "*.pdf"
      
website:
  title: "Andrew Reeves"
  description: "Professor of Political Science, Director of the Weidenbaum Center, and Senior Advisor to the Chancellor | Washington University in St. Louis"
  
  navbar:
    background: "#BA0C2F"  # WashU Red
    foreground: "#ffffff"
    pinned: true
    logo: "images/washu-logo/WashU-Reverse_web.png"  # WashU full color logo
    logo-alt: "Washington University in St. Louis"
    
    left:
      - href: index.qmd
        text: Home
      - href: research/
        text: Research
      - href: teaching/
        text: Teaching
      - href: news/
        text: News
      - href: contact/
        text: Contact
        
    right:
      - href: reevescv.pdf
        text: CV
        icon: file-earmark-pdf
      - icon: envelope
        href: mailto:reeves@wustl.edu
        aria-label: Email
      - icon: linkedin
        href: https://www.linkedin.com/in/areeves/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/ajreeves
        aria-label: GitHub
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=YourScholarID
        aria-label: Google Scholar
      - icon: chat-square-text
        href: https://bsky.app/profile/ajreeves.bsky.social
        aria-label: Bluesky

  page-footer:
    background: "#13322B"  # WashU Dark Green
    foreground: "#ffffff"
    left: |
      © 2025 Andrew Reeves
    right: |
      Political Science | Weidenbaum Center
    center: |
      Washington University in St. Louis

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: false
    page-layout: full
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 200px
    css: 
      - styles.scss
    
    # WashU brand-compliant metadata
    lang: en
    title-prefix: "Andrew Reeves | Washington University in St. Louis"
    
    # Professional academic styling
    anchor-sections: true
    smooth-scroll: true
    citations-hover: true
    crossrefs-hover: true
    
    # SEO and meta tags
    description-meta: "Professor of Political Science, Director of the Weidenbaum Center, and Senior Advisor to the Chancellor at Washington University in St. Louis"
    
    # WashU brand-compliant fonts
    include-in-header: 
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,400&display=swap" rel="stylesheet">
          <meta name="theme-color" content="#BA0C2F">
          <meta name="keywords" content="political science, public policy, Washington University, WashU, American politics">
    
    # Social media and SEO
    open-graph:
      image: "images/andrew-reeves-headshot.jpg"
      locale: en_US
      site-name: "Andrew Reeves - Washington University in St. Louis"

bibliography: references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/american-political-science-association.csl

# WashU-specific metadata (removed author/affiliation to prevent top-of-page display)
  
# Professional academic website settings
execute:
  freeze: auto
  
# Additional WashU branding elements (moved to format section)